config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }

  resources :tweets do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "tweets#index"

end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :comments , dependent: :destroy
    validates :tweet , presence: true
end 

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets

  has_one_attached :image, :dependent => :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    # rescue_from CanCan::AccessDenied do |exception|
    #     redirect_to root_url, alert: exception.message
    # end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password, :image])
  end 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @tweet = Tweet.find(params[:tweet_id])
        @comment = @tweet.comments.create(comment_params)
        
        respond_to do |format|
            format.html { redirect_to tweet_path(@tweet) }
            format.js 
        end
    end

    def destroy
        @tweet = Tweet.find(params[:tweet_id])
        @comment = @tweet.comments.find(params[:id])
        @comment.destroy
        redirect_to tweet_path(@tweet), status: 303
        
    end
    
    private
    def comment_params
        params.require(:comment).permit(:body)
    end         
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
    private
      def after_confirmation_path_for(resource_name, resource)
        sign_in(resource)
        new_user_session_path
      end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
    
    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :user_id )
    end
    
    def account_update_params
     params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :name, :image)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]
  before_action :authenticate_user! 
  

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order("created_at DESC")
    @tweet = Tweet.new
    # @tweet = current_user.tweets.build
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)
    @tweet.user_id = current_user.id

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'User was successfully created.'}
        format.js  {}
        # format.json { render :show, status: :created, location: @tweet }
        format.json { render :index, status: :created, location: @tweet }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
        format.js  {}
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy
    redirect_to tweets_url, status: 303
    # respond_to do |format|
    #   format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper


    def user_image(user,size=40)
        if user.image.attached?
          user.image.variant(resize:"#{size}x#{size}!")
        else
          # gravatar_image_url(user.email,size:size)
          # asset_path 'male.jpg' 
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/_comment.html.erb
<p>
    <strong>Comment:</strong>
    <%= comment.body %>
</p>
<%if current_user || tweet.user %>
<%= link_to "Del", [comment.tweet, comment], :confirm => 'Are you sure?', :method => :delete, remote: true%>
<%end%>
<hr>

app/views/comments/_form.html.erb
<%= form_with(model: [ @tweet, @tweet.comments.build], local: false, id:"comments-form" ) do |f| %>
    <div class="form-group" >
        <%= f.text_area :body, class: "form-control" , placeholder:"Add a comment:" %>
    </div>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/comments/create.js.erb
$('#com').html("<%=j render @tweet.comments %>");
document.querySelector('#comments-form').reset();

app/views/comments/destroy.js .erb
console.log('Binding event');
$('.delete_comment').bind('ajax:success', function() {
  console.log('fading the element: ', $(this).closest('tr')); 
  $(this).closest('tr').fadeOut();
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Twitter</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <!--For UJS and then asset.rb file  -->
        <%= javascript_include_tag 'application' %>
        
    </head>

    <body> 
        
        <%= yield %>
        
    </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="container">
    <div class="alert <%= type == "notice" ? 'alert-success' : 'alert-danger' %>" role="alert">
      <%= message %>
    </div>
  </div>
<% end %>

app/views/shared/_validation-messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
        <p class="font-weight-bold"><%= pluralize(object.errors.count, "error") %> prohibited this <%= "#{object.class.name.downcase}" %> from being saved:</p>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: false, id: "tweets-form" ) do |f| %>
  <%= render "shared/validation-messages", object: f.object %>

    <div class="form-group" >
       <h3><%= f.label :tweet %></h3>
        <%= f.text_area :tweet, class: "form-control" , placeholder:"What's happening?" %>
    </div>
   <div class="btn-group">
        <%= f.submit class: "btn btn-success" %>
        <%# NOTE Only show the delete button on the edit page. Otherwise it would appear when adding a new post. %>
        <% if params[:action] == 'edit' && current_user %>
            <%= link_to "Delete Tweet", tweet_path(@tweet), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>        
        <% end %>
    </div>
<% end %>

app/views/tweets/_tweet.html.erb
<article class="card mb-3 post post-<%= tweet.id %>">
    <%
=begin%>
 <div class="card-header">
        <h3 class="mb-0">Tweet</h3>
    </div> 
<%
=end%>
    <div class="card-body">

            <%= image_tag tweet.user.image, style:"width:40px;height:40px",class:"rounded-circle" if tweet.user.image.attached? %>
 
        <small class="d-inline-block mb-3 text-secondary border-bottom">Posted by: <%= tweet.user.name %> <%= time_ago_in_words(tweet.created_at) %> ago.</small> 
        <h4><p class="card-text"><%= tweet.tweet %></p></h4>
        <%if current_user.id == tweet.user_id %>
            <%= link_to 'Edit', edit_tweet_path(tweet), class: "btn btn-sm btn-outline-primary" %>
            <%= link_to 'Destroy', tweet, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %>
            <%= link_to 'Comment', tweet ,  class: "btn btn-sm btn-outline-primary"%>
        <%else%>
            <%= link_to 'Comment', tweet %>
        <%end%>
        <p></p>
        <!-- Comment -->
        <div class="container">
            <div id="com">
                <%= render tweet.comments %>
            </div>
        </div>
    </div>
</article><br>

app/views/tweets/create.js.erb
<% if @tweet.errors.any? %>
    <%# This removes any error messages that were previously generated. %>
    document.querySelector('#error_explanation') ? document.querySelector('#error_explanation').remove() : null ;
    <%# This selects the `<form>` in and dynamically injects the `app/views/shared/_validation-messages.html.erb` partial. %>
    document.querySelector('#tweets-form').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render "shared/validation-messages", object: @tweet) %>');
<% else %>
    <%# This removes any error messages that were previously generated. %>
    document.querySelector('#error_explanation') ? document.querySelector('#error_explanation').remove() : null ;
    <%# This selects `<div id="tweets">` and dynamically injects the `app/views/tweets/_tweet.html.erb` partial. %>
    document.querySelector('#tweets').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render @tweet) %>') ;
    <%# This selects the `<form>` and resets the text area. %>
    document.querySelector('#tweets-form').reset();
<% end %>

app/views/tweets/edit.html.erb
<div class="container position-relative px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="card">
                <div class="card-header">
                    <h1 class="mb-0">Edit <%= @tweet.tweet %></h1>
                </div>
                <div class="card-body">
                    <%= render "form" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/tweets/index.html.erb
 <%if signed_in? %>
        <div class="container">
            <div class="row py-3">
                <div class="col-3" id="sticky-sidebar">
                    <div class="sticky-top">
                        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav mr-auto flex-column vertical-nav">
                                    <%if signed_in?%>
                                        <li class="nav-item text-center">
                                        <%if current_user.image.attached?%>
                                           <%= image_tag user_image(current_user,170),class:"rounded-circle" %>  
                                        <%else%>
                                           <%= image_tag("", class:"rounded-circle") %> 
                                        <%end%>
                                        </li><br> 
                                    <%end%>
                                    <li class="nav-item text-center">
                                        <h1><strong><%= current_user.name.upcase%></strong></h1>
                                    </li>                                   
                                    <li class="nav-item">
                                        <a class="dropdown-item" href="<%= edit_user_registration_path%>">Edit Profile</a>
                                    </li>
                                    <li class="nav-item">
                                         <a class="dropdown-item" href="<%= destroy_user_session_path%>" data-method="delete">Sign Out</a>
                                    </li>
                                    
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
                <div class="col-5" id="main">
                    <%if (notice || alert).present?%>
                        <p class="notice"><%= notice %></p>
                        <p class="alert"><%= alert %></p>
                        <%= render 'form', tweet: @tweet %><br> 
                    <%else%>
                        <%= render 'form', tweet: @tweet %><br>
                    <%end%>
                    <div id="tweets" >
                        <% Tweet.all.each do |tweet| %>
                            <%= render tweet%>
                        <% end %>
                    </div>            
                </div>
                <div class="col-4 order-2"  id="sticky-sidebar">
                <div class="sticky-top" >
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav mr-auto flex-column vertical-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="<%= root_path%>">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="<%= new_user_session_path%>">Log In</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Setting</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                       <%= current_user.name%>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="<%= edit_user_registration_path%>">Edit Profile</a>
                                    <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="<%= destroy_user_session_path%>" data-method="delete">Sign Out</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
<%else%>
    <div class="container">
        <div class="col-5">
            <%if (notice || alert).present?%>
                <p class="notice"><%= notice %></p>
                <p class="alert"><%= alert %></p>
                <%= render 'form', tweet: @tweet %><br> 
            <%else%>
                <%= render 'form', tweet: @tweet %><br>
            <%end%>
            <div id="tweets" >
                <% Tweet.all.each do |tweet| %>
                    <%= render tweet%>
                <% end %>
            </div>            
        </div>
    </div>
<%end%>

app/views/tweets/new.html.erb
<div id="page_wrapper">
  <h1>New Tweet</h1>
  <%= render 'form', tweet: @tweet%>
  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="container">
    <div class="row py-3">
        <div class="col-3" id="sticky-sidebar">
            <div class="sticky-top">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto flex-column vertical-nav">
                            <%if signed_in?%>
                                <li class="nav-item text-center">
                                <%if current_user.image.attached?%>
                                    <%= image_tag user_image(current_user,170),class:"rounded-circle" %>  
                                <%else%>
                                    <%= image_tag("", class:"rounded-circle") %> 
                                <%end%>
                                </li><br> 
                            <%end%>
                            <li class="nav-item text-center">
                                <h1><strong><%= current_user.name.upcase%></strong></h1>
                            </li>                                   
                            <li class="nav-item">
                                <a class="dropdown-item" href="<%= edit_user_registration_path%>">Edit Profile</a>
                            </li>
                            <li class="nav-item">
                                  <a class="dropdown-item" href="<%= destroy_user_session_path%>" data-method="delete">Sign Out</a>
                            </li>
                            
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <div class="col-5" id="main">
           <p id="notice"><%= notice %></p>

            <p>
              <strong>Tweet:</strong>
              <%= @tweet.tweet %>
            </p>
            <div id='com'>
                <%= render @tweet.comments %>
            </div>

            <%= render 'comments/form' %>

            <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
            <%= link_to 'Back', tweets_path %>
        </div>
        <div class="col-4 order-2"  id="sticky-sidebar">
        <div class="sticky-top" >
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto flex-column vertical-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="<%= root_path%>">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<%= new_user_session_path%>">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Setting</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <%= current_user.name%>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="<%= edit_user_registration_path%>">Edit Profile</a>
                            <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="<%= destroy_user_session_path%>" data-method="delete">Sign Out</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</div>